In [2]:
import numpy as np
x = [1, 2, 3, 4, 5]
y = [i * 2 + 1 for i in x]

class LinearRegression:
    def __init__(self, features_train, labels_train):
        self.features = self.add_bias_column(features_train)
        self.weights = np.random.rand(len(self.features[0]))
        self.labels = np.array(labels_train)
    def add_bias_column(self, data):
        # add extra column of which elements are all 1 in order to put bias in weight vector, not adding bias separately to hypothesis
        new_data = np.array(data)
        if new_data.ndim == 0:
            new_data = [new_data] + [1]
            return new_data
        if new_data.ndim == 1:
            new_data = new_data[:, np.newaxis]
        bias_column = [[1] for i in range(len(data))]
        new_data = np.append(new_data, bias_column, axis=1)
        return new_data
    def hypothesis(self, features):
        return np.matmul(features, self.weights)
    def cost(self, hypothesis, labels):
        return ((hypothesis - labels) ** 2).sum() / 2
    def grad(self, features, hypothesis, labels):
        return np.matmul(np.transpose(features), (hypothesis - labels))
    def gradient_descent(self, lr, EPOCHS):
        for step in range(EPOCHS + 1):
            hypothesis = self.hypothesis(self.features)
            gradients = self.grad(self.features, hypothesis, self.labels)
            self.weights = self.weights - lr * gradients
            cost = self.cost(hypothesis, self.labels)
            if step % (EPOCHS / 10) == 0:
                print("{:6} : cost {:10.4f}".format(step, cost))
    def train(self, lr, EPOCHS):
        self.gradient_descent(lr, EPOCHS)
        print("Training is complete.")
    def test(self, features_test, labels_test):
        features = self.add_bias_column(features_test)
        hypothesis = self.hypothesis(features)
        print("Estimate Value: {:10.4f} | Answer: {} | Test Error Rate: {:10.4f}%".format(hypothesis, labels_test, np.abs(labels_test - hypothesis) / labels_test * 100))
model = LinearRegression(x, y)
model.train(0.01, 1000)
x_test = 327
model.test(x_test, x_test * 2 + 1)

     0 : cost    49.3960
   100 : cost     0.0090
   200 : cost     0.0017
   300 : cost     0.0003
   400 : cost     0.0001
   500 : cost     0.0000
   600 : cost     0.0000
   700 : cost     0.0000
   800 : cost     0.0000
   900 : cost     0.0000
  1000 : cost     0.0000
Training is complete.
Estimate Value:   655.0060 | Answer: 655 | Test Error Rate:     0.0009%


In [3]:
# curve fit
import numpy as np
x = [1, 2, 3, 4, 5]
y = [i ** 2 + 1 for i in x]

def nth_poly(vector, degree):
    data = [[x ** i for i in range(1, degree + 1)] for x in vector]
    return data

x = nth_poly(x, 2)

class LinearRegression:
    def __init__(self, features_train, labels_train):
        self.features = self.add_bias_column(features_train)
        self.weights = np.random.rand(len(self.features[0]))
        self.labels = np.array(labels_train)
    def add_bias_column(self, data):
        # add extra column of which elements are all 1 in order to put bias in weight vector, not adding bias separately to hypothesis
        new_data = np.array(data)
        if new_data.ndim == 0:
            new_data = [new_data] + [1]
            return new_data
        if new_data.ndim == 1:
            new_data = new_data[:, np.newaxis]
        bias_column = [[1] for i in range(len(data))]
        new_data = np.append(new_data, bias_column, axis=1)
        return new_data
    def hypothesis(self, features):
        return np.matmul(features, self.weights)
    def cost(self, hypothesis, labels):
        return ((hypothesis - labels) ** 2).sum() / 2
    def grad(self, features, hypothesis, labels):
        return np.matmul(np.transpose(features), (hypothesis - labels))
    def gradient_descent(self, lr, EPOCHS):
        for step in range(EPOCHS + 1):
            hypothesis = self.hypothesis(self.features)
            gradients = self.grad(self.features, hypothesis, self.labels)
            self.weights = self.weights - lr * gradients
            cost = self.cost(hypothesis, self.labels)
            if step % (EPOCHS / 10) == 0:
                print("{:6} : cost {:10.4f}".format(step, cost))
    def train(self, lr, EPOCHS):
        self.gradient_descent(lr, EPOCHS)
        print("Training is complete.")
    def test(self, features_test, labels_test):
        features = self.add_bias_column(features_test)
        hypothesis = self.hypothesis(features)
        print("Estimate Value: {:10.4f} | Answer: {} | Test Error Rate: {:10.4f}%".format(hypothesis[0], labels_test, (np.abs(labels_test - hypothesis) / labels_test * 100)[0]))
model = LinearRegression(x, y)
model.train(0.001, 10000)
x_test = 327
features_test = nth_poly([x_test], 2)
model.test(features_test, x_test ** 2 + 1)

     0 : cost    10.8076
  1000 : cost     0.0547
  2000 : cost     0.0413
  3000 : cost     0.0312
  4000 : cost     0.0236
  5000 : cost     0.0178
  6000 : cost     0.0135
  7000 : cost     0.0102
  8000 : cost     0.0077
  9000 : cost     0.0058
 10000 : cost     0.0044
Training is complete.
Estimate Value: 104501.4363 | Answer: 106930 | Test Error Rate:     2.2712%


In [4]:
# Normal Equation
import numpy as np
x = [1, 2, 3, 4, 5]
y = [i ** 2 * 127 + i * 256 + 324 for i in x]

def nth_poly(vector, degree):
    data = [[x ** i for i in range(1, degree + 1)] for x in vector]
    return data
def add_bias_column(data):
    # add extra column of which elements are all 1 in order to put bias in weight vector, not adding bias separately to hypothesis
    new_data = np.array(data)
    bias_column = [[1] for i in range(len(data))]
    new_data = np.append(new_data, bias_column, axis=1)
    return new_data

x = add_bias_column(nth_poly(x, 2))
print(x)
theta = np.matmul(np.linalg.inv(np.matmul(np.transpose(x), x)), np.matmul(np.transpose(x), y))
print(theta)

[[ 1  1  1]
 [ 2  4  1]
 [ 3  9  1]
 [ 4 16  1]
 [ 5 25  1]]
[256. 127. 324.]
